# Generated by Django 4.0.6 on 2022-07-28 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_advuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdvUser',
        ),
    ]
